// 100 riddles. `id` is stable and used as the localStorage key for solved state —
// never renumber these, only append.
const RIDDLES = [
  { id: 1, q: "The more you take, the more you leave behind. What am I?", a: "Footsteps" },
  { id: 2, q: "I have keys but no locks. I have space but no room. What am I?", a: "A keyboard" },
  { id: 3, q: "I get wetter the more I dry. What am I?", a: "A towel" },
  { id: 4, q: "I have a face and two hands, but no arms or legs. What am I?", a: "A clock" },
  { id: 5, q: "I'm tall when I'm young and short when I'm old. What am I?", a: "A candle" },
  { id: 6, q: "The more you remove from me, the bigger I become. What am I?", a: "A hole" },
  { id: 7, q: "I have many teeth but cannot bite. What am I?", a: "A comb" },
  { id: 8, q: "I can travel around the world while staying in one corner. What am I?", a: "A stamp" },
  { id: 9, q: "I have one eye but cannot see. What am I?", a: "A needle" },
  { id: 10, q: "I'm full of holes, but I can still hold water. What am I?", a: "A sponge" },
  { id: 11, q: "What has a neck but no head?", a: "A bottle" },
  { id: 12, q: "What has hands but cannot clap?", a: "A clock" },
  { id: 13, q: "What has words but never speaks?", a: "A book" },
  { id: 14, q: "What can run but never walks?", a: "Water" },
  { id: 15, q: "What has a thumb and four fingers but isn't alive?", a: "A glove" },
  { id: 16, q: "What comes down but never goes up?", a: "Rain" },
  { id: 17, q: "What gets bigger the more you feed it, but dies if you give it water?", a: "Fire" },
  { id: 18, q: "What belongs to you, but other people use it more than you do?", a: "Your name" },
  { id: 19, q: "What has cities, roads, and rivers but no people, cars, or water?", a: "A map" },
  { id: 20, q: "What can you catch but never throw?", a: "A cold" },
  { id: 21, q: "What has a head and a tail but no body?", a: "A coin" },
  { id: 22, q: "What goes up and down but never moves?", a: "Stairs" },
  { id: 23, q: "What has four legs but cannot walk?", a: "A table" },
  { id: 24, q: "What has an eye at the center but cannot see?", a: "A hurricane" },
  { id: 25, q: "What can be cracked, made, told, and played?", a: "A joke" },
  { id: 26, q: "What has a ring but no finger?", a: "A telephone" },
  { id: 27, q: "What has a bed but never sleeps?", a: "A river" },
  { id: 28, q: "What has a mouth but never eats?", a: "A river" },
  { id: 29, q: "What has branches but no leaves, fruit, or flowers?", a: "A bank" },
  { id: 30, q: "What can fill a room but takes up no space?", a: "Light" },
  { id: 31, q: "What disappears the moment you say its name?", a: "Silence" },
  { id: 32, q: "What is always in front of you but can never be seen?", a: "The future" },
  { id: 33, q: "What has lots of eyes but cannot see?", a: "A potato" },
  { id: 34, q: "What has ears but cannot hear?", a: "Corn" },
  { id: 35, q: "What has a bottom at the top?", a: "Your legs" },
  { id: 36, q: "What can you hold without ever touching it?", a: "Your breath" },
  { id: 37, q: "What gets shorter every time it takes a bath?", a: "A bar of soap" },
  { id: 38, q: "What has no life but can still die?", a: "A battery" },
  { id: 39, q: "What goes through cities and fields but never moves?", a: "A road" },
  { id: 40, q: "What has a spine but no bones?", a: "A book" },
  { id: 41, q: "What has a head, a foot, and four legs?", a: "A bed" },
  { id: 42, q: "What can be opened but has no door?", a: "A book" },
  { id: 43, q: "What has a tongue but cannot talk?", a: "A shoe" },
  { id: 44, q: "What has a heart that never beats?", a: "An artichoke" },
  { id: 45, q: "What can you hear but not see or touch?", a: "Sound" },
  { id: 46, q: "What has 13 hearts but no other organs?", a: "A deck of cards" },
  { id: 47, q: "What is easy to lift but hard to throw?", a: "A feather" },
  { id: 48, q: "What starts with T, ends with T, and has T in it?", a: "A teapot" },
  { id: 49, q: "What is black when you buy it, red when you use it, and gray when you throw it away?", a: "Charcoal" },
  { id: 50, q: "The more there is of me, the less you can see. What am I?", a: "Darkness" },
  { id: 51, q: "I have no voice, but I can tell you a story. What am I?", a: "A book" },
  { id: 52, q: "I'm always running, but I never get tired. What am I?", a: "A river" },
  { id: 53, q: "What has a lot of keys but can't open a single door?", a: "A piano" },
  { id: 54, q: "What can you see once in a minute, twice in a moment, but never in a thousand years?", a: "The letter M" },
  { id: 55, q: "What has a head but no brain?", a: "A nail" },
  { id: 56, q: "What has legs but doesn't walk, and a seat but doesn't sit?", a: "A chair" },
  { id: 57, q: "What can fly without wings and cry without eyes?", a: "A cloud" },
  { id: 58, q: "What has a face but no eyes, nose, or mouth?", a: "A clock" },
  { id: 59, q: "What has an end but no beginning, a home but no family, and a space without a room?", a: "The letter E" },
  { id: 60, q: "What can you make that nobody can see?", a: "A promise" },
  { id: 61, q: "What has a lock but no door?", a: "A lock of hair" },
  { id: 62, q: "What can jump higher than a building?", a: "Anything — buildings can't jump" },
  { id: 63, q: "What has a bottom but no top?", a: "A leg" },
  { id: 64, q: "What can be seen once in a year, twice in a week, but never in a day?", a: "The letter E" },
  { id: 65, q: "What has four wheels and flies?", a: "A garbage truck" },
  { id: 66, q: "What kind of tree can you carry in your hand?", a: "A palm tree" },
  { id: 67, q: "What has a face, but no body?", a: "A clock" },
  { id: 68, q: "What gets broken without being touched?", a: "A promise" },
  { id: 69, q: "What can you serve but never eat?", a: "A tennis ball" },
  { id: 70, q: "What has a lot of money but cannot spend any of it?", a: "A bank" },
  { id: 71, q: "What has a bark but no bite?", a: "A tree" },
  { id: 72, q: "What can you hold in your right hand but never in your left hand?", a: "Your left hand" },
  { id: 73, q: "What is always coming but never arrives?", a: "Tomorrow" },
  { id: 74, q: "What has a lot of rings but no fingers?", a: "A telephone" },
  { id: 75, q: "What can be seen in the middle of March and April but not at the beginning or end of either month?", a: "The letter R" },
  { id: 76, q: "What is something you can't use until you break it?", a: "An egg" },
  { id: 77, q: "What has no beginning, end, or middle?", a: "A circle" },
  { id: 78, q: "What goes up when the rain comes down?", a: "An umbrella" },
  { id: 79, q: "What has a head like a cat, feet like a cat, but isn't a cat?", a: "A kitten" },
  { id: 80, q: "What is so fragile that saying its name breaks it?", a: "Silence" },
  { id: 81, q: "What can you never put in a saucepan?", a: "Its lid" },
  { id: 82, q: "What has a tail and a head but no legs?", a: "A coin" },
  { id: 83, q: "What kind of coat is always wet when you put it on?", a: "A coat of paint" },
  { id: 84, q: "What has a lot of letters but isn't the alphabet?", a: "A mailbox" },
  { id: 85, q: "What is at the end of a rainbow?", a: "The letter W" },
  { id: 86, q: "What has no weight but can sink a ship?", a: "A hole" },
  { id: 87, q: "What can you find in the middle of nowhere?", a: "The letter H" },
  { id: 88, q: "What has a mouth on its head and feet at the bottom?", a: "A person" },
  { id: 89, q: "What can go up a chimney down, but can't go down a chimney up?", a: "An umbrella" },
  { id: 90, q: "What is made of water but dies if you put it in water?", a: "Ice" },
  { id: 91, q: "What has a thumb and fingers but isn't a hand?", a: "A glove" },
  { id: 92, q: "What can be long or short, grown or bought, painted or left bare?", a: "Nails" },
  { id: 93, q: "What has many needles but doesn't sew?", a: "A pine tree" },
  { id: 94, q: "What can you always find in the last place you look?", a: "The thing you're looking for" },
  { id: 95, q: "What has one foot on each side and one in the middle?", a: "A yardstick" },
  { id: 96, q: "What has a face and hands but no arms or legs, and tells you something without speaking?", a: "A clock" },
  { id: 97, q: "What has a lot of eyes but cannot see, and grows underground?", a: "A potato" },
  { id: 98, q: "What can be broken even if you never pick it up or touch it?", a: "A promise" },
  { id: 99, q: "What has a head, a tail, is brown, and has no legs?", a: "A penny" },
  { id: 100, q: "What is light as a feather, but even the strongest person can't hold it for much longer than a minute?", a: "Your breath" },
];
